yarn firestore:copy config firebase-config.json
yarn firestore:copy gallery firebase-gallery.json
yarn firestore:copy notificationsSubscribers firebase-notificationsSubscribers.json
yarn firestore:copy partners firebase-partners.json
yarn firestore:copy schedule firebase-schedule.json
yarn firestore:copy sessions firebase-sessions.json
yarn firestore:copy speakers firebase-speakers.json
yarn firestore:copy team firebase-team.json
yarn firestore:copy tickets firebase-tickets.json
